Javadoc error fix for CUCorrectionProposal.setDelegate()
See https://download.eclipse.org/eclipse/downloads/drops4/I20230925-1800/compilelogs/jdt.doc.isv.javadoc.txt

../../../eclipse.jdt.ui/org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/text/java/correction/CUCorrectionProposal.java:147:
error: @param name not found
	 * @param delegate to set
	          ^

Regression from 816a5d21cf7c29294915c50bd95503e0462eff02